

name: Run Eslint
on:
  push:
   branches:
     - main

jobs:
 runningEslint:
  runs-on: ubuntu-latest
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install node
      uses: actions/setup-node@v2
      with:
       node-version: "16.x"
    - name: print node version
      run: node -v  
    - name: install dependencies
      run: npm install
    - name: run Eslint
      run: npx eslint      


